name: Update Image List
on:
  push:
    paths:
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate JSON
        run: |
          # 不再切换目录，直接在根目录操作
          echo '{"images": [' > list.json
          ls -1 images/*.jpg images/*.png | awk -F/ '{printf "\"%s\",", $2}' >> list.json
          sed -i '$ s/,$//' list.json
          echo ']}' >> list.json
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add list.json  # 正确添加根目录下的文件
          git commit -m "Update image list"
          git pull --rebase origin main
          git push origin main