name: Update Image List

on:
  push:
    paths:
      - 'images/**'

permissions:
  contents: write  # 授予写入权限

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史记录

      - name: Generate List
        run: |
          # 生成 list.json 的实际脚本（替换占位符）
          # 示例：扫描 images 目录并生成 JSON 数组
          echo '{"images": [' > list.json
          ls -1 images/*.jpg images/*.png 2>/dev/null | awk -F/ '{printf "\"%s\",", $2}' >> list.json
          sed -i '$ s/,$//' list.json  # 删除末尾逗号
          echo ']}' >> list.json

          # 处理空目录情况（若 images 为空，生成空数组）
          if [ ! -s list.json ]; then
            echo '{"images": []}' > list.json
          fi

      - name: Validate list.json
        run: |
          if [ ! -f list.json ]; then
            echo "❌ list.json 未生成！"
            exit 1
          fi
          # 检查 JSON 格式是否合法
          if ! jq empty list.json; then
            echo "❌ list.json 格式错误！"
            exit 1
          fi

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add list.json
          
          # 检查是否有变更需要提交
          if git diff-index --quiet HEAD --; then
            echo "⚠️ 无文件变更，跳过提交。"
          else
            git commit -m "Auto Update List"
            git pull --rebase origin main
            git push origin main
          fi