name: Update Image List

on:
  push:
    paths:
      - 'images/**'  # 仅当 images 目录内容变化时触发

permissions:
  contents: write  # 允许工作流写入仓库内容（推送代码）

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 使用最新版本
        with:
          fetch-depth: 0  # 拉取完整提交历史

      - name: Generate List
        run: |
          # 生成 list.json 的脚本
          echo '[]' > list.json  # 替换为生成 list.json 的实际脚本

      - name: Check list.json existence
        run: |
          if [ ! -f list.json ]; then
            echo "list.json not found!"
            exit 1
          fi

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add list.json
          git commit -m "Auto Update List"
          git pull --rebase origin main  # 同步最新代码
          git push origin main